baseURL: https://wearetechnative.github.io/yumyum/
languageCode: en-us
title: Yum Yum at TechNative
theme: summer-qremix
params:
  tagline: 🥩 Delicious recipes by TechNative's 🥒
  copyright: >-
    © 2023 [The people from
    TechNative](https://github.com/wearetechnative/yumyum). All rights reserved.
  links:
    - name: GitHub
      url: https://github.com/mipmip/summer-qremix
    - name: The Quiqr Book
      url: https://book.quiqr.org
  moreLinksTitle: More Themes
  moreLinks:
    - name: Spring
      url: https://connor-baer.github.io/spring
    - name: Autumn
      url: https://connor-baer.github.io/autumn
  color: '#FF5900'
  font: Rubik
  resources: []
  header_image: photo_2023-06-08_13-39-11.jpg
  logo_image: coolguy2.svg
  favicon_image: logo4github.png
markup:
  goldmark:
    renderer:
      unsafe: true
