baseURL: https://wearetechnative.github.io/yumyum/
languageCode: en-us
title: Yum Yum at TechNative
theme: summer-qremix
params:
  tagline: 🥩 Delicious recipes by TechNatives 🥒
  copyright: >-
    © 2023 [The people from TechNative](https://technative.eu). All rights
    reserved.
  links:
    - name: GitHub
      url: https://github.com/wearetechnative/yumyum
    - name: TechNative Company
      url: https://technative.eu
  moreLinksTitle: More links
  moreLinks:
    - name: Quiqr
      url: https://quiqr.org
    - name: Hugo
      url: https://gohugo.io
  color: '#FF5900'
  font: Rubik
  resources: []
  header_image: photo_2023-06-08_13-39-11.jpg
  logo_image: coolguy2.svg
  favicon_image: logo4github.png
markup:
  goldmark:
    renderer:
      unsafe: true
